version: '3'
services: 
   shoppingoback:
      build: ../
      links:
         - "db:db_host"
      volumes: 
      - ../shoppingo_api:/opt/app/shoppingo_api/
      ports: 
      - "8000:8020"
      depends_on:
         - db
   db:
      image: mysql:5.7
      ports:
         - 3306:3306
      environment:
         MYSQL_ROOT_PASSWORD: mydjangoapp
         MYSQL_USER: mydjangoapp
         MYSQL_PASSWORD: mydjangoapp
         MYSQL_DATABASE: mydjangoapp
      healthcheck:
         test: ["CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost"]
         timeout: 20s
         retries: 10
      restart: always
      volumes:
         - ../database/data:/var/lib/mysql  
#    application_db:
#        build: ../databases/postgres_application_db
#        volumes:
#            - ../databases/postgres_application_db/postgres-data:/var/lib/postgresql/data
  

   
        
        
